spring.application.name=paymentintegration
spring.datasource.url=jdbc:mysql://localhost:3306/pay
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.secret.key=${RAZORPAY_SECRET}



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true